server:
  port: 8081
  servlet:
    context-path: /npbg
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 12345
    dynamic:
      # 此处的druid配置为全局配置，以下所有数据源都会遵循，但以下数据源也可以重新设置以覆盖它
      druid:
        initial-size: 0
        max-active: 20
        min-idle: 5
        max-wait: 60000
      # primary属性必须设置，值为下列数据源中的一个，比如改为udts
      primary: master
      datasource:
        master:
          username: *
          password: *
          # 可写可不写， 数据源会自动识别数据库驱动
          # driverClassName: com.mysql.cj.jdbc.Driver
          url: *
        udts:
          username: *
          password: *
          # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: *
        itms_original:
          username: *
          password: *
          # driverClassName: com.mysql.cj.jdbc.Driver
          url: *
  redis:
    host: *
    port: *
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000ms
mybatis:
  mapper-locations:
    - classpath:com/foxconn/npbg/dao/*.xml

logging:
  level:
    com.foxconn.npbg.dao: debug
    root: info