server:
  port: 8081
  servlet:
    context-path: /npbg
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 12345
    dynamic:
      # 此处的druid配置为全局配置，以下所有数据源都会遵循，但以下数据源也可以重新设置以覆盖它
      druid:
        initial-size: 0
        max-active: 20
        min-idle: 5
        max-wait: 60000
      # primary属性必须设置，值为下列数据源中的一个，比如改为udts
      primary: master
      datasource:
        master:
          username: root
          password: wang2702
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
#        udts:
#          username: sa
#          password: Wstg168!!!
#          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://10.167.219.229:3000
#        itms:
#          username: shawn
#          password: shawn
#          # 因为这个itms数据库是mysql5.7，所以这里就不填写driverClassName
#          url: jdbc:mysql://10.167.219.240:3306
  redis:
    host: 10.132.46.51
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000ms
logging:
  level:
    root: info